### PR TITLE
Start up MongoDB instance in CI process resolves se701g2/Doto/#46

### PR DESCRIPTION
**Pull request by lucycy98**

### CODE REVIEW

**Comment by allenwang968** [comment]
> * added line 'mongod' in nodjs.yml file
> * added npm test in backend package.js

**Comment by res550** [comment]
```
    - name: Install MongoDB
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org
        sudo apt-get install -y mongodb-org=3.6.14 mongodb-org-server=3.6.14 mongodb-org-shell=3.6.14 mongodb-org-mongos=3.6.14 mongodb-org-tools=3.6.14
    - name: Start MongoDB
      run: sudo systemctl start mongod
```

we could try this to run mongo from CI logs looks like mongo is not installed. It will probably be slow but we could run this in a different CI so it runs in parallel with the frontend tests

**Comment by res550** [comment]
I'll try the above on my own fork and let you know if it works. So we can get these tests running

**Comment by lucycy98** [comment]
Okay awesome, thank you!

**Comment by res550** [comment]
Sure I can pick up this ticket

**Comment by lucycy98** [comment]
@res550 tests are running for backend now!! but i also fixed a small mistake in the yml file (it was running backend tests twice), and so thats failed..

**Pull request merged**
