### PR TITLE
Create LICENSE resolves se701g2/Doto#4

### PR DESCRIPTION
**Pull request by daltonlim**
Resolves se701g2/Doto#4
Reasoning behind the choice can be found in the [wiki](https://github.com/se701g2/Doto/wiki/License)

### CODE REVIEW

**Comment by daltonlim** [comment]
Hi @cwon880. That is a good point you bring up and I shall add a name. Does our team have a formal name or should I use se3701g2?

**Comment by cwon880** [comment]
@daltonlim  Yea that sounds good, I don't think we have decided on a team name just yet so maybe lets leave this pr open until then

**Comment by res550** [comment]
I think we should use se701g2 as our name since we have it as the organisation name. But I think we may be able to change it so I would be open to just seeing what others want to do

**Comment by cwon880** [comment]
@daltonlim looks our team name will be taffy, so maybe change it to that?

**Comment by Dinith1** [comment]
@cwon880 maybe we should just choose a Team name at our meeting tomorrow

**Comment by cwon880** [comment]
@daltonlim I think we might have to choose license at the end, depending on any frameworks of dependencies we have used which may require a specific license as Kelly has pointed out in class.

**Comment by daltonlim** [comment]
Yeah, that's a good point. I'll leave this open for now.

**Pull request closed without merging**
