### PR TITLE
issue/264 - Support drag and drop of calendar events closes #264

### LINKED ISSUE #264: Support drag and drop of calendar events
### User Story: 

As an end user, I want to be able to drag-and-drop calendar events to modify their start/end dates. I also want to be able to resize calendar events to modify their duration.

### Acceptance Criteria:

1) Support drag-and-drop of calendar events
2) Support resizing of calendar events

### Why is the feature required?

Facilitates better ease of use. 

### Describe the solution you'd like

Able to drag and drop calendar events. Able to drag the borders of calendar events to resize them.

### PR DESCRIPTION
**Pull request by Minus20Five**
Demo.

* Support drag-and-drop of calendar events using dev-express DragDropProvider
* Support resizing of calendar events
* Events updated on server side
* Reminder-date updated based on new start-date 
(note this means if you move an event which has already fired off a reminder, a new reminder may be fired off based on the new start date. This is expected behaviour for now.)

ezgif-3-05edf402456f

- [x] The pull request is complete according to the following criteria:
  - [x] Acceptance criteria have been met
  - [x] The documentation is kept up-to-date
  - [x] Comprehensive tests (if applicable) have been generated and all pass.
  - [x] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
  - [x] Commits have been squashed (or will be on merge).
  - [x] The branch name is descriptive and follows the pull request title format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [x] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [x] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
  - [x] At least two reviewers assigned. One of which must be the assigner of the issue.
  - [x] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by Minus20Five** [comment]
> Looks great, makes it a lot nicer to drag the boxes around.
> 
> It doesn't look like you update the task duration if the length gets changed though. While this doesn't affect anything currently, it might affect the edit PR.
> 
> I also noticed that if you drag an item to a later time, then add a new one, it will just get added onto the end of the last task rather than going before it where there is free time. This will probably be better as a new issue (bug) though.

**Comment by Minus20Five** [comment]
Whoops, ignore accidental delete.

@KimberleyEvans-Parker and @rmoradc thanks for the comments.

I will recompute the duration and sort the tasks by startdate and see if that fixes the issues.

**Comment by Kalashnikkov** [comment]
Hey @Minus20Five I appreciate the changes you've made!

I was working on issue #224 and it seems like when this is pushed through, I could add functionality extending this PR onto mine. Thoughts?

**Comment by Minus20Five** [comment]
> Hey @Minus20Five I appreciate the changes you've made!
> 
> I was working on issue #224 and it seems like when this is pushed through, I could add functionality extending this PR onto mine. Thoughts?

If you decide to implement recurring tasks I would recommend following the [dev express API](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/appointments/#recurring-appointments). Theres also a built-in component to [edit recurring tasks](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/edit-recurrence-menu/).

**Pull request merged**
