### PR TITLE
Issue/#64-document-backend-api

### PR DESCRIPTION
**Pull request by tigerj2**
- [ ] The pull request is complete according to the following criteria:
  - [ ] Acceptance criteria have been met
  - [ ] The documentation is kept up-to-date
  - [ ] Comprehensive tests (if applicable) have been generated and all pass.
  - [ ] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
  - [ ] Commits have been squashed (or will be on merge).
  - [ ] The branch name is descriptive and follows the pull request title format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
  - [ ] At least two reviewers assigned. One of which must be the assigner of the issue.
  - [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by lucycy98** [comment]
any reason why this PR has 10 commits?

**Comment by tigerj2** [comment]
> the changes in the file look good :) but any reason why this PR has 10 commits?

My git terminal was doing weird things so I had to do a bunch of merges with this branch and the master. Nothing is changed except the api doc in this pr 😊

**Comment by res550** [comment]
Hey @tigerj2 could you take a look at the conflicts other than that this looks really well done and will be able to go ahead and merge it

**Comment by tigerj2** [comment]
@lucycy98 I have fixed the merging issues. Should be ready for the merge into master now.

**Comment by daltonlim** [comment]
@lucycy98 @tigerj2 The file was deleted in pull request #177 . Have the changes been integrated and can this be closed?

**Comment by lucycy98** [comment]
also note: the api docs were updated since the last changes were made but i will just keep that in mind when adding stuff to wiki

**Pull request closed without merging**
