### PR TITLE
bug/252-Fix checkbox not updating by abstracting state away from component renders closes #252

### LINKED ISSUE #252: Checkbox in to-do list items doesn't update correctly
### Bug Summary: 
When marking a task as 'complete' through the calendar view, the checkbox in the list view is not filled.

--- 

### Steps To Reproduce

1) Create a task
2) Open the list view
3) Mark the task as complete by clicking on the task in the calendar
4) Observe

### Expected behaviour

When a task is marked as complete in the calendar view, the corresponding item in the task list has its checkbox filled.

### Observed Behaviour

When a task is marked as complete in the calendar view, the corresponding item in the task list does not have its checkbox filled.

### Screenshots

DotoBug

### Environment

- Version: 9fab8f0
- Operating System: Windows/Arch Linux
- Browser (if any): Firefox v69

---

### Stack Traces
N/A
### Test Cases
N/A
### Code Examples
N/A
### Error Reports
N/A
### Other
N/A

### PR DESCRIPTION
**Pull request by PreetPatel**
- [x] The pull request is complete according to the following criteria:
  - [ ] Acceptance criteria have been met
  - [ ] The documentation is kept up-to-date
  - [ ] Comprehensive tests (if applicable) have been generated and all pass.
  - [ ] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
  - [ ] Commits have been squashed (or will be on merge).
  - [ ] The branch name is descriptive and follows the pull request title format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
  - [ ] At least two reviewers assigned. One of which must be the assigner of the issue.
  - [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by PreetPatel** [comment]
> It crosses out the task on the checklist and the task is marked as complete which is good. However, the actual checkbox doesn't get ticked. If there's no way to get the checkbox to be ticked through code then I guess it's alright since the actual task is marked as complete, but it's just a cosmetic problem.

It did the tick for me when i ran it.. thats weird

**Comment by PreetPatel** [comment]
> Hi @PreetPatel ,
> 
> Thanks for working on this bug. I think that I might have found a new bug while checking this code out locally. When first accessing Doto I get the following:
> 
> * After the authentication the following exception is thrown, "Unhandled Rejection (Type Error): Cannot read property 'themePreference". Although, there is a button to cross it out and proceed.
> * This then loads the home page, when trying to create a new task the following is thrown: "Cannot read property 'forEach"
> 
> I have attached screenshots below for reference (To document with the bug).
> image
> image
> 
> NOTE:
> After doing a refresh everything works as supposed to and I do not get the issue @EricPedrido mentioned. Thanks for fix @PreetPatel 👍. Thus, since everything does seem to work I have gone ahead and approved the PR and will make a bug report for what I encountered, and hopefully, we can triangulate it soon.

Cheers thanks @harmanlamba

**Comment by EricPedrido** [comment]
>  I do not get the issue @EricPedrido mentioned
Alright, well I assume it's a problem on my end then, I'll remove my change request but I won't be approving it just in case someone else gets this issue too. Nice work though, everything else looks good.

**Comment by jordansimsmith** [comment]
Hey @PreetPatel, can you elaborate on why this is a fix? It looks functionally equivalent to me.

**Comment by HarrisonLeach1** [comment]
> Hey @PreetPatel, can you elaborate on why this is a fix? It looks functionally equivalent to me.

I agree, the behaviour from #252 can still be replicated. The checkbox should work with having to refresh the page.

**Comment by jordansimsmith** [comment]
Closing for now, feel free to reopen when its ready to be merged in :)

**Comment by PreetPatel** [comment]
Rip.. just started working on it haha

**Pull request closed without merging**
