### PR TITLE
Bug/294 can't edit task due to earliest date addition

### LINKED ISSUE #294: Can't edit task due to earliestDate addition
### Bug Summary: 
TaskScheduler tries to access earliestDate in an existing task but can't because it is not stored in the Task model database

--- 

### Steps To Reproduce

1) Add a task with any parameter
2) Edit the task
3) Submit

### Expected behaviour

Task should be saved with new parameters

### Observed Behaviour

Web page shows the debug page

### Environment

- Version: latest
- Operating System: Windows 10
- Browser (if any):  Google Chrome

---

### PR DESCRIPTION
**Pull request by nikotj1**
- Edited UpdateModalContent to have Earliest Date
- earliestDate is now a field for the Task model in the back-end
- DotoSevices now sends earliestDate as a field as well

Closes #294 
- [x] The pull request is complete according to the following criteria:
  - [ ] Acceptance criteria have been met
  - [ ] The documentation is kept up-to-date
  - [ ] Comprehensive tests (if applicable) have been generated and all pass.
  - [ ] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
  - [ ] Commits have been squashed (or will be on merge).
  - [ ] The branch name is descriptive and follows the pull request title format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
  - [ ] At least two reviewers assigned. One of which must be the assigner of the issue.
  - [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by jordansimsmith** [comment]
Hey @nikotj1 , I get this error when editing a task.

ss

**Comment by jordansimsmith** [comment]
I also get this error logged in the backend
```
"task validation failed: startDate: Cast to Date failed for value \"Invalid Date\" at path \"startDate\", endDate: Cast to Date failed for value \"Invalid Date\" at path \"endDate\", earliestDate: Cast to Date failed for value \"Invalid Date\" at path \"earliestDate\""
```

**Comment by nikotj1** [comment]
Added validation in an attempt to fix the bug.

**Comment by nikotj1** [comment]
@all-contributors please add @nikotj1 for bug, design

**Pull request merged**
