### PR TITLE
Enhancement/#59-Configuring-tailwind-css-with-frontend

### PR DESCRIPTION
**Pull request by FocalChord**
I have configured tailwind css by installing it via npm and then writing the correct configuration for it.

This PR closes issue #59 

- [x] The pull request is complete according to the following criteria:
  - [x] Acceptance criteria have been met
  - [x] The documentation is kept up-to-date
  - [ ] Comprehensive tests (if applicable) have been generated and all pass.
- [x] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
- [x] Commmits have been squashed
- [x] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
- [x] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
- [x] At least two reviewers assigned. One of which must be the assigner of the issue.
- [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by res550** [comment]
Hey, would this mean that we would need to update the CD to run the css build?

**Comment by Dinith1** [comment]
> Hey, would this mean that we would need to update the CD to run the css build?

@res550 What is involved in the CD? I think this PR is just adding a dependency

**Comment by FocalChord** [comment]
> Hey, would this mean that we would need to update the CD to run the css build?

@res550 It is configured this in `npm start` and `npm build` so this shouldn't be a problem.

**Comment by res550** [comment]
@FocalChord okay cool just making sure

**Comment by res550** [comment]
w

> > Hey, would this mean that we would need to update the CD to run the css build?
> 
> @res550 What is involved in the CD? I think this PR is just adding a dependency

Our CI/CD builds the frontend and backend and then runs the tests on them

**Comment by lakshyaoberoi** [comment]
> w
> 
> > > Hey, would this mean that we would need to update the CD to run the css build?
> > 
> > 
> > @res550 What is involved in the CD? I think this PR is just adding a dependency
> 
> Our CI/CD builds the frontend and backend and then runs the tests on them

Correct. Usually the CI/CD build will run `npm start` and `npm build`. The build should also run the tests.

**Pull request merged**
