### PR TITLE
Enhancement/#67-Setup Router with sample pages

### LINKED ISSUE #67: Setup Default Routing
### User Story: 

As a software developer, I want to set up default Routing to have the ability to navigate through different pages. 

### Acceptance Criteria:

1) User should be able to navigate into different pages
2) Any pages that are not found should navigate the user to NotFound page

### Why is this Feature Needed?

We need a routing system so that users have the ability to navigate into different pages

### PR DESCRIPTION
**Pull request by Cvos0162**
This PR sets up the basic Routing system.
'/' will route to Main Page
'/settings' will route to Settings Page
'/calendar' will route to Calendar Page
Any other will route to 404 page

This PR resolves #67

- [x] The pull request is complete according to the following criteria:
  - [x] Acceptance criteria have been met
  - [ ] The documentation is kept up-to-date
  - [x] Comprehensive tests (if applicable) have been generated and all pass.
- [x] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
- [ ] Commmits have been squashed
- [x] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
- [x] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
- [ ] At least two reviewers assigned. One of which must be the assigner of the issue.
- [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by Cvos0162** [comment]
@MarioSinovcic sorry I missed one, can you look at it again?

**Comment by Cvos0162** [comment]
> Sorry not quite sure what common.js means? maybe a better name if possible?

any suggestions? maybe route.js?

**Comment by MarioSinovcic** [comment]
Yeah thats way better to me, sorry to nit-pick 😬

**Comment by Cvos0162** [comment]
> Yeah thats way better to me, sorry to nit-pick 😬

Nah I wasn't thinking too careful about it. was just looking into what other ppl done to file hierarchy for react

**Comment by Cvos0162** [comment]
> I just have one question, in index.js is there any reason you removed the import React from "react"? Sorry if it's nitpicky, I just wanted to confirm it wasn't a mistake or something

husky picked this up saying that this is not needed. I could include them but there is no need.
Also, I reckon leaving anything that is not needed is a bad coding practice

**Pull request merged**
