### PR TITLE
Refactor/#108-Use promise to use .catch statement

### LINKED ISSUE #108: Use Promises when communicating with db
### User Story: 

As a software engineer, I want to use Promises class so that 
1) it is a better way to handle async operation
2) It is much more self-documenting code then using if statement to catch the error

Promise comes naturally in js. No package has to be given
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

### Acceptance Criteria:
Change the if statement catching an error and use .catch statement with Promises.
1) router.get for /users
2) router.post for /users

### PR DESCRIPTION
**Pull request by Cvos0162**
.save() and .find() is async function. We want to use Promise to handle these operations

resolves #108

- [ ] The pull request is complete according to the following criteria:
  - [ ] Acceptance criteria have been met
  - [ ] The documentation is kept up-to-date
  - [ ] Comprehensive tests (if applicable) have been generated and all pass.
  - [ ] The pull request describes the changes that have been made, and enough information is present in the description for any developer to understand what has changed
  - [ ] Commits have been squashed (or will be on merge).
  - [ ] The branch name is descriptive and follows the pull request title format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The pull request title is of the following format : {issue/bug...}/(Issue Number) - Name of issue. E.g bug/30-Fix-Project
  - [ ] The description uses [github syntax](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to link to the issue. E,g Resolves se701g2/Doto#{Number}
  - [ ] At least two reviewers assigned. One of which must be the assigner of the issue.
  - [ ] If there are merge conflicts, run git rebase as opposed to git merge with master.

### CODE REVIEW

**Comment by tnzhu** [comment]
@Cvos0162 Heya, backend is working on this, so I don't think this will go through.

**Comment by Cvos0162** [comment]
> @Cvos0162 Heya, backend is working on this, so I don't think this will go through.

Oh, that's cool. I was just passing by and thought this was good coding practice.
Anyway, the issue is still valid since there are no changes in the code. Please make sure to reference the issue #108 on the new PR, when someone actually handles them.
(Although I think, there is no reason to pick this PR up, but that's ok)

**Comment by res550** [comment]
Hey @Cvos0162 and @tnzhu whats the status for the other can we close this one

**Comment by tnzhu** [comment]
> Hey @Cvos0162 and @tnzhu whats the status for the other can we close this one

Yeah, I think the plan is to refactor once all changes are made.

**Comment by res550** [comment]
Okay cool that sounds good

**Pull request closed without merging**
